# @package _group_

fairseq:
  task:
    _name: unpaired_audio_text
    labels: phn
    data: '/unsupervised/data/librispeech_preprocessed/audio100/precompute_pca512_cls128_mean'
    sort_by_length: false
    shuffle: false
    text_data: ''
  #common:
  #  user_dir: ''
  common_eval:
    path: '/unsupervised/data/gan_checkpoints/gan_checkpoint_last.pt'
    quiet: true

  dataset:
    gen_subset: test
    batch_size: 1

w2l_decoder: KALDI
post_process: silence

unit_lm: false
targets: wrd
blank_weight: 0
sil_is_blank: true
blank_mode: set
unsupervised_tuning: false
results_path: outputs

kaldi_decoder_config:
  hlg_graph_path: '/unsupervised/data/librispeech_preprocessed/text-lm-10/fst/phn_to_words_sil/HLG.phn.kenlm.wrd.o40003.fst' 
  output_dict: '/unsupervised/data/librispeech_preprocessed/text-lm-10/fst/phn_to_words_sil/kaldi_dict.kenlm.wrd.o40003.txt'
