# @package _group_

fairseq:
  task:
    _name: unpaired_audio_text
    labels: phn
    data: '/unsupervised/data/librispeech_preprocessed/audio100/precompute_pca512_cls128_mean_pooled'
    sort_by_length: false
    shuffle: false
    text_data: ''

  common_eval:
    path: '/unsupervised/data/gan_checkpoints/gan_checkpoint_last.pt'
    quiet: true

  dataset:
    gen_subset: valid
    batch_size: 1

w2l_decoder: VITERBI
post_process: silence

unit_lm: false
targets: phn
blank_weight: 0
sil_is_blank: true
blank_mode: set
unsupervised_tuning: false